// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: media.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (name, url, type)
VALUES ($1, $2, $3)
RETURNING id,url
`

type CreateMediaParams struct {
	Name *string `db:"name" json:"name"`
	Url  *string `db:"url" json:"url"`
	Type *string `db:"type" json:"type"`
}

type CreateMediaRow struct {
	ID  uuid.UUID `db:"id" json:"id"`
	Url *string   `db:"url" json:"url"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (CreateMediaRow, error) {
	row := q.db.QueryRow(ctx, createMedia, arg.Name, arg.Url, arg.Type)
	var i CreateMediaRow
	err := row.Scan(&i.ID, &i.Url)
	return i, err
}

const deleteMediaByID = `-- name: DeleteMediaByID :one
DELETE FROM media
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteMediaByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteMediaByID, id)
	err := row.Scan(&id)
	return id, err
}

const deleteMediaByIdBulk = `-- name: DeleteMediaByIdBulk :exec
DELETE FROM media
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteMediaByIdBulk(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaByIdBulk, dollar_1)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, name, url, type, created_at FROM media
WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getUnusedMedia = `-- name: GetUnusedMedia :many
SELECT id, url
FROM media
WHERE reference_count <= 0
  AND created_at < NOW() - INTERVAL '1 day'
`

type GetUnusedMediaRow struct {
	ID  uuid.UUID `db:"id" json:"id"`
	Url *string   `db:"url" json:"url"`
}

func (q *Queries) GetUnusedMedia(ctx context.Context) ([]GetUnusedMediaRow, error) {
	rows, err := q.db.Query(ctx, getUnusedMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnusedMediaRow{}
	for rows.Next() {
		var i GetUnusedMediaRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
