// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleUSER      UserRole = "USER"
	UserRoleADMIN     UserRole = "ADMIN"
	UserRoleMODERATOR UserRole = "MODERATOR"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusACTIVE      UserStatus = "ACTIVE"
	UserStatusSUSPENDED   UserStatus = "SUSPENDED"
	UserStatusDEACTIVATED UserStatus = "DEACTIVATED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	Action        *string         `db:"action" json:"action"`
	EntityID      uuid.NullUUID   `db:"entity_id" json:"entity_id"`
	EntityType    string          `db:"entity_type" json:"entity_type"`
	ActionDetails json.RawMessage `db:"action_details" json:"action_details"`
	IpAddress     *netip.Addr     `db:"ip_address" json:"ip_address"`
	Timestamp     *time.Time      `db:"timestamp" json:"timestamp"`
}

type Medium struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Name      *string    `db:"name" json:"name"`
	Url       *string    `db:"url" json:"url"`
	Type      *string    `db:"type" json:"type"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID                uuid.UUID     `db:"id" json:"id"`
	Name              string        `db:"name" json:"name"`
	Username          *string       `db:"username" json:"username"`
	Email             string        `db:"email" json:"email"`
	PhoneNumber       *string       `db:"phone_number" json:"phone_number"`
	IsEmailVerified   bool          `db:"is_email_verified" json:"is_email_verified"`
	IsDeleted         bool          `db:"is_deleted" json:"is_deleted"`
	IsVerified        bool          `db:"is_verified" json:"is_verified"`
	Password          *string       `db:"password" json:"password"`
	PasswordChangedAt *time.Time    `db:"password_changed_at" json:"password_changed_at"`
	GoogleID          *string       `db:"google_id" json:"google_id"`
	AppleID           *string       `db:"apple_id" json:"apple_id"`
	Role              UserRole      `db:"role" json:"role"`
	UserType          *string       `db:"user_type" json:"user_type"`
	Status            UserStatus    `db:"status" json:"status"`
	ProfileImage      *string       `db:"profile_image" json:"profile_image"`
	CurrentPlan       uuid.NullUUID `db:"current_plan" json:"current_plan"`
	StripeCustomerID  *string       `db:"stripe_customer_id" json:"stripe_customer_id"`
	SubEndDate        *time.Time    `db:"sub_end_date" json:"sub_end_date"`
	ResetToken        *string       `db:"reset_token" json:"reset_token"`
	ResetExpires      *time.Time    `db:"reset_expires" json:"reset_expires"`
	CreatedAt         *time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt         *time.Time    `db:"updated_at" json:"updated_at"`
}

type UserMedium struct {
	UserID      uuid.UUID  `db:"user_id" json:"user_id"`
	MediaID     uuid.UUID  `db:"media_id" json:"media_id"`
	Type        *string    `db:"type" json:"type"`
	Name        *string    `db:"name" json:"name"`
	Description *string    `db:"description" json:"description"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
}

type UserProfile struct {
	UserID              uuid.UUID       `db:"user_id" json:"user_id"`
	ProfileBannerUrl    *string         `db:"profile_banner_url" json:"profile_banner_url"`
	Bio                 *string         `db:"bio" json:"bio"`
	Thought             *string         `db:"thought" json:"thought"`
	ProfessionalSummary *string         `db:"professional_summary" json:"professional_summary"`
	ExperienceLevel     *string         `db:"experience_level" json:"experience_level"`
	Profession          *string         `db:"profession" json:"profession"`
	ProfessionDetails   json.RawMessage `db:"profession_details" json:"profession_details"`
	Gender              *string         `db:"gender" json:"gender"`
	DateOfBirth         *time.Time      `db:"date_of_birth" json:"date_of_birth"`
	CreatedAt           *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt           *time.Time      `db:"updated_at" json:"updated_at"`
}

type UserSession struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	UserID           uuid.UUID   `db:"user_id" json:"user_id"`
	RefreshTokenHash string      `db:"refresh_token_hash" json:"refresh_token_hash"`
	UserAgent        *string     `db:"user_agent" json:"user_agent"`
	IpAddress        *netip.Addr `db:"ip_address" json:"ip_address"`
	CreatedAt        *time.Time  `db:"created_at" json:"created_at"`
	LastSeenAt       *time.Time  `db:"last_seen_at" json:"last_seen_at"`
	ExpiresAt        time.Time   `db:"expires_at" json:"expires_at"`
	RevokedAt        *time.Time  `db:"revoked_at" json:"revoked_at"`
}
