// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ChangeAccountStatus(ctx context.Context, arg ChangeAccountStatusParams) (ChangeAccountStatusRow, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (CreateMediaRow, error)
	CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (CreateResetTokenRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (CreateUserSessionRow, error)
	DeleteMediaByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	DeleteMediaByIDBulk(ctx context.Context, dollar_1 []uuid.UUID) error
	DeleteOldSessions(ctx context.Context) error
	GetAllUserIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error)
	GetOfflineUsers(ctx context.Context) ([]uuid.UUID, error)
	GetPasswordByID(ctx context.Context, id uuid.UUID) (*string, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (GetSessionByIDRow, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GetSessionByRefreshTokenHashRow, error)
	GetUnusedMedia(ctx context.Context) ([]GetUnusedMediaRow, error)
	GetUserByAppleID(ctx context.Context, appleID *string) (GetUserByAppleIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByGoogleID(ctx context.Context, googleID *string) (GetUserByGoogleIDRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByResetToken(ctx context.Context, resetToken *string) (GetUserByResetTokenRow, error)
	GetUserCredentialByID(ctx context.Context, id uuid.UUID) (GetUserCredentialByIDRow, error)
	GetUserEmailByID(ctx context.Context, id uuid.UUID) (string, error)
	GetUserStripeInfoByEmail(ctx context.Context, email string) (GetUserStripeInfoByEmailRow, error)
	GetUserStripeInfoByID(ctx context.Context, id uuid.UUID) (GetUserStripeInfoByIDRow, error)
	RevokeSessionByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) (UpdateEmailStatusRow, error)
	UpdatePasswordByID(ctx context.Context, arg UpdatePasswordByIDParams) error
	UpdatePasswordReset(ctx context.Context, arg UpdatePasswordResetParams) (UpdatePasswordResetRow, error)
	UpdateProfileImage(ctx context.Context, arg UpdateProfileImageParams) (UpdateProfileImageRow, error)
	UpdateSessionLastSeen(ctx context.Context, id uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
