// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const changeAccountStatus = `-- name: ChangeAccountStatus :one
UPDATE
    users
SET
    STATUS = $1
WHERE
    id = $2 RETURNING id,
    name,
    email
`

type ChangeAccountStatusParams struct {
	Status UserStatus `db:"status" json:"status"`
	ID     uuid.UUID  `db:"id" json:"id"`
}

type ChangeAccountStatusRow struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Name  string    `db:"name" json:"name"`
	Email string    `db:"email" json:"email"`
}

func (q *Queries) ChangeAccountStatus(ctx context.Context, arg ChangeAccountStatusParams) (ChangeAccountStatusRow, error) {
	row := q.db.QueryRow(ctx, changeAccountStatus, arg.Status, arg.ID)
	var i ChangeAccountStatusRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const createResetToken = `-- name: CreateResetToken :one
UPDATE
    users
SET
    reset_token = $1,
    reset_expires = $2
WHERE
    email = $3 RETURNING id,
    name,
    email,
    reset_token,
    role,
    reset_expires
`

type CreateResetTokenParams struct {
	ResetToken   *string    `db:"reset_token" json:"reset_token"`
	ResetExpires *time.Time `db:"reset_expires" json:"reset_expires"`
	Email        string     `db:"email" json:"email"`
}

type CreateResetTokenRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Email        string     `db:"email" json:"email"`
	ResetToken   *string    `db:"reset_token" json:"reset_token"`
	Role         UserRole   `db:"role" json:"role"`
	ResetExpires *time.Time `db:"reset_expires" json:"reset_expires"`
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (CreateResetTokenRow, error) {
	row := q.db.QueryRow(ctx, createResetToken, arg.ResetToken, arg.ResetExpires, arg.Email)
	var i CreateResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ResetToken,
		&i.Role,
		&i.ResetExpires,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        name,
        email,
        phone_number,
        username,
        PASSWORD,
        google_id,
        apple_id,
        is_email_verified
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    ) RETURNING id,
    name,
    username,
    email,
    phone_number,
    role
`

type CreateUserParams struct {
	Name            string  `db:"name" json:"name"`
	Email           string  `db:"email" json:"email"`
	PhoneNumber     *string `db:"phone_number" json:"phone_number"`
	Username        *string `db:"username" json:"username"`
	Password        *string `db:"password" json:"password"`
	GoogleID        *string `db:"google_id" json:"google_id"`
	AppleID         *string `db:"apple_id" json:"apple_id"`
	IsEmailVerified bool    `db:"is_email_verified" json:"is_email_verified"`
}

type CreateUserRow struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Username    *string   `db:"username" json:"username"`
	Email       string    `db:"email" json:"email"`
	PhoneNumber *string   `db:"phone_number" json:"phone_number"`
	Role        UserRole  `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.Username,
		arg.Password,
		arg.GoogleID,
		arg.AppleID,
		arg.IsEmailVerified,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
WITH existing_session AS (
    SELECT
        EXISTS (
            SELECT
                1
            FROM
                user_sessions
            WHERE
                user_sessions.user_id = $1
        ) AS has_sessions
),
new_session AS (
    INSERT INTO
        user_sessions (
            user_id,
            refresh_token_hash,
            user_agent,
            ip_address,
            expires_at
        )
    VALUES
        ($1, $2, $3, $4, $5) RETURNING id
)
SELECT
    new_session.id,
    NOT existing_session.has_sessions AS first_login
FROM
    new_session,
    existing_session
`

type CreateUserSessionParams struct {
	UserID           uuid.UUID   `db:"user_id" json:"user_id"`
	RefreshTokenHash string      `db:"refresh_token_hash" json:"refresh_token_hash"`
	UserAgent        *string     `db:"user_agent" json:"user_agent"`
	IpAddress        *netip.Addr `db:"ip_address" json:"ip_address"`
	ExpiresAt        time.Time   `db:"expires_at" json:"expires_at"`
}

type CreateUserSessionRow struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	FirstLogin pgtype.Bool `db:"first_login" json:"first_login"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (CreateUserSessionRow, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i CreateUserSessionRow
	err := row.Scan(&i.ID, &i.FirstLogin)
	return i, err
}

const deleteOldSessions = `-- name: DeleteOldSessions :exec
DELETE FROM
    user_sessions
WHERE
    (
        revoked_at IS NOT NULL
        AND revoked_at < NOW() - INTERVAL '90 days'
    )
    OR (expires_at < NOW() - INTERVAL '90 days')
`

func (q *Queries) DeleteOldSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldSessions)
	return err
}

const getAllUserIds = `-- name: GetAllUserIds :many
SELECT
    id
FROM
    users
WHERE
    id <> $1
`

func (q *Queries) GetAllUserIds(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAllUserIds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOfflineUsers = `-- name: GetOfflineUsers :many
SELECT DISTINCT user_id
FROM user_sessions
WHERE last_seen_at < NOW() - INTERVAL '1 minute'
LIMIT 1000
`

func (q *Queries) GetOfflineUsers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getOfflineUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordById = `-- name: GetPasswordById :one
SELECT
    PASSWORD
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetPasswordById(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getPasswordById, id)
	var password *string
	err := row.Scan(&password)
	return password, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
    id,
    user_id,
    revoked_at,
    last_seen_at,
    expires_at
FROM
    user_sessions
WHERE
    id = $1
    AND expires_at > NOW()
`

type GetSessionByIDRow struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	UserID     uuid.UUID  `db:"user_id" json:"user_id"`
	RevokedAt  *time.Time `db:"revoked_at" json:"revoked_at"`
	LastSeenAt *time.Time `db:"last_seen_at" json:"last_seen_at"`
	ExpiresAt  time.Time  `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT
    id,
    user_id
FROM
    user_sessions
WHERE
    refresh_token_hash = $1
    AND revoked_at IS NULL
    AND expires_at > NOW()
`

type GetSessionByRefreshTokenHashRow struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GetSessionByRefreshTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i GetSessionByRefreshTokenHashRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getUserByAppleId = `-- name: GetUserByAppleId :one
SELECT
    id,
    name,
    email,
    phone_number,
    username,
    PASSWORD,
    google_id,
    apple_id,
    is_email_verified
FROM
    users
WHERE
    apple_id = $1
`

type GetUserByAppleIdRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Name            string    `db:"name" json:"name"`
	Email           string    `db:"email" json:"email"`
	PhoneNumber     *string   `db:"phone_number" json:"phone_number"`
	Username        *string   `db:"username" json:"username"`
	Password        *string   `db:"password" json:"password"`
	GoogleID        *string   `db:"google_id" json:"google_id"`
	AppleID         *string   `db:"apple_id" json:"apple_id"`
	IsEmailVerified bool      `db:"is_email_verified" json:"is_email_verified"`
}

func (q *Queries) GetUserByAppleId(ctx context.Context, appleID *string) (GetUserByAppleIdRow, error) {
	row := q.db.QueryRow(ctx, getUserByAppleId, appleID)
	var i GetUserByAppleIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.Password,
		&i.GoogleID,
		&i.AppleID,
		&i.IsEmailVerified,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    name,
    email,
    phone_number,
    username,
    PASSWORD,
    google_id,
    apple_id,
    role,
    STATUS,
    is_email_verified
FROM
    users
WHERE
    email = $1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID  `db:"id" json:"id"`
	Name            string     `db:"name" json:"name"`
	Email           string     `db:"email" json:"email"`
	PhoneNumber     *string    `db:"phone_number" json:"phone_number"`
	Username        *string    `db:"username" json:"username"`
	Password        *string    `db:"password" json:"password"`
	GoogleID        *string    `db:"google_id" json:"google_id"`
	AppleID         *string    `db:"apple_id" json:"apple_id"`
	Role            UserRole   `db:"role" json:"role"`
	Status          UserStatus `db:"status" json:"status"`
	IsEmailVerified bool       `db:"is_email_verified" json:"is_email_verified"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.Password,
		&i.GoogleID,
		&i.AppleID,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
	)
	return i, err
}

const getUserByGoogleId = `-- name: GetUserByGoogleId :one
SELECT
    id,
    name,
    email,
    phone_number,
    username,
    PASSWORD,
    google_id,
    apple_id,
    is_email_verified
FROM
    users
WHERE
    google_id = $1
`

type GetUserByGoogleIdRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Name            string    `db:"name" json:"name"`
	Email           string    `db:"email" json:"email"`
	PhoneNumber     *string   `db:"phone_number" json:"phone_number"`
	Username        *string   `db:"username" json:"username"`
	Password        *string   `db:"password" json:"password"`
	GoogleID        *string   `db:"google_id" json:"google_id"`
	AppleID         *string   `db:"apple_id" json:"apple_id"`
	IsEmailVerified bool      `db:"is_email_verified" json:"is_email_verified"`
}

func (q *Queries) GetUserByGoogleId(ctx context.Context, googleID *string) (GetUserByGoogleIdRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleId, googleID)
	var i GetUserByGoogleIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.Password,
		&i.GoogleID,
		&i.AppleID,
		&i.IsEmailVerified,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
   u.id,
   u.name,
   u.email,
   u.phone_number,
   u.username,
   u.google_id,
   u.apple_id,
   u.is_email_verified,
   u.profile_image,
   u.role,
   u.user_type,
   u.STATUS,
    (
        u.PASSWORD IS NOT NULL
        AND length(u.PASSWORD) > 0
    ) AS has_password
FROM
    users u
WHERE
    u.id = $1
`

type GetUserByIdRow struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Email           string      `db:"email" json:"email"`
	PhoneNumber     *string     `db:"phone_number" json:"phone_number"`
	Username        *string     `db:"username" json:"username"`
	GoogleID        *string     `db:"google_id" json:"google_id"`
	AppleID         *string     `db:"apple_id" json:"apple_id"`
	IsEmailVerified bool        `db:"is_email_verified" json:"is_email_verified"`
	ProfileImage    *string     `db:"profile_image" json:"profile_image"`
	Role            UserRole    `db:"role" json:"role"`
	UserType        *string     `db:"user_type" json:"user_type"`
	Status          UserStatus  `db:"status" json:"status"`
	HasPassword     pgtype.Bool `db:"has_password" json:"has_password"`
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.GoogleID,
		&i.AppleID,
		&i.IsEmailVerified,
		&i.ProfileImage,
		&i.Role,
		&i.UserType,
		&i.Status,
		&i.HasPassword,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT
    id,
    reset_expires
FROM
    users
WHERE
    reset_token = $1
`

type GetUserByResetTokenRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	ResetExpires *time.Time `db:"reset_expires" json:"reset_expires"`
}

func (q *Queries) GetUserByResetToken(ctx context.Context, resetToken *string) (GetUserByResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, resetToken)
	var i GetUserByResetTokenRow
	err := row.Scan(&i.ID, &i.ResetExpires)
	return i, err
}

const getUserCredentialById = `-- name: GetUserCredentialById :one
SELECT
    email,
    PASSWORD,
    name
FROM
    users
WHERE
    id = $1
`

type GetUserCredentialByIdRow struct {
	Email    string  `db:"email" json:"email"`
	Password *string `db:"password" json:"password"`
	Name     string  `db:"name" json:"name"`
}

func (q *Queries) GetUserCredentialById(ctx context.Context, id uuid.UUID) (GetUserCredentialByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialById, id)
	var i GetUserCredentialByIdRow
	err := row.Scan(&i.Email, &i.Password, &i.Name)
	return i, err
}

const getUserEmailById = `-- name: GetUserEmailById :one
SELECT
    email
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserEmailById(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmailById, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getUserStripeInfoByEmail = `-- name: GetUserStripeInfoByEmail :one
SELECT
    id,
    stripe_customer_id
FROM
    users
WHERE
    email = $1
`

type GetUserStripeInfoByEmailRow struct {
	ID               uuid.UUID `db:"id" json:"id"`
	StripeCustomerID *string   `db:"stripe_customer_id" json:"stripe_customer_id"`
}

func (q *Queries) GetUserStripeInfoByEmail(ctx context.Context, email string) (GetUserStripeInfoByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserStripeInfoByEmail, email)
	var i GetUserStripeInfoByEmailRow
	err := row.Scan(&i.ID, &i.StripeCustomerID)
	return i, err
}

const getUserStripeInfoById = `-- name: GetUserStripeInfoById :one
SELECT
    email,
    name,
    stripe_customer_id
FROM
    users
WHERE
    id = $1
`

type GetUserStripeInfoByIdRow struct {
	Email            string  `db:"email" json:"email"`
	Name             string  `db:"name" json:"name"`
	StripeCustomerID *string `db:"stripe_customer_id" json:"stripe_customer_id"`
}

func (q *Queries) GetUserStripeInfoById(ctx context.Context, id uuid.UUID) (GetUserStripeInfoByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserStripeInfoById, id)
	var i GetUserStripeInfoByIdRow
	err := row.Scan(&i.Email, &i.Name, &i.StripeCustomerID)
	return i, err
}

const revokeSessionById = `-- name: RevokeSessionById :one
UPDATE
    user_sessions
SET
    revoked_at = NOW()
WHERE
    id = $1 RETURNING user_id
`

func (q *Queries) RevokeSessionById(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeSessionById, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateEmailStatus = `-- name: UpdateEmailStatus :one
UPDATE
    users
SET
    is_email_verified = $1
WHERE
    id = $2 RETURNING id,
    is_email_verified,
    email
`

type UpdateEmailStatusParams struct {
	IsEmailVerified bool      `db:"is_email_verified" json:"is_email_verified"`
	ID              uuid.UUID `db:"id" json:"id"`
}

type UpdateEmailStatusRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	IsEmailVerified bool      `db:"is_email_verified" json:"is_email_verified"`
	Email           string    `db:"email" json:"email"`
}

func (q *Queries) UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) (UpdateEmailStatusRow, error) {
	row := q.db.QueryRow(ctx, updateEmailStatus, arg.IsEmailVerified, arg.ID)
	var i UpdateEmailStatusRow
	err := row.Scan(&i.ID, &i.IsEmailVerified, &i.Email)
	return i, err
}

const updatePasswordById = `-- name: UpdatePasswordById :exec
UPDATE
    users
SET
    PASSWORD = $1
WHERE
    id = $2
`

type UpdatePasswordByIdParams struct {
	Password *string   `db:"password" json:"password"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdatePasswordById(ctx context.Context, arg UpdatePasswordByIdParams) error {
	_, err := q.db.Exec(ctx, updatePasswordById, arg.Password, arg.ID)
	return err
}

const updatePasswordReset = `-- name: UpdatePasswordReset :one
UPDATE
    users
SET
    PASSWORD = $1,
    reset_token = NULL,
    reset_expires = NULL
WHERE
    (
        id = $2
        AND reset_token = $3
    ) RETURNING id,
    name
`

type UpdatePasswordResetParams struct {
	Password   *string   `db:"password" json:"password"`
	ID         uuid.UUID `db:"id" json:"id"`
	ResetToken *string   `db:"reset_token" json:"reset_token"`
}

type UpdatePasswordResetRow struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) UpdatePasswordReset(ctx context.Context, arg UpdatePasswordResetParams) (UpdatePasswordResetRow, error) {
	row := q.db.QueryRow(ctx, updatePasswordReset, arg.Password, arg.ID, arg.ResetToken)
	var i UpdatePasswordResetRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateProfileImage = `-- name: UpdateProfileImage :one
UPDATE
    users
SET
    profile_image = $1
WHERE
    id = $2 RETURNING id,
    name,
    email,
    phone_number,
    username,
    profile_image
`

type UpdateProfileImageParams struct {
	ProfileImage *string   `db:"profile_image" json:"profile_image"`
	ID           uuid.UUID `db:"id" json:"id"`
}

type UpdateProfileImageRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Email        string    `db:"email" json:"email"`
	PhoneNumber  *string   `db:"phone_number" json:"phone_number"`
	Username     *string   `db:"username" json:"username"`
	ProfileImage *string   `db:"profile_image" json:"profile_image"`
}

func (q *Queries) UpdateProfileImage(ctx context.Context, arg UpdateProfileImageParams) (UpdateProfileImageRow, error) {
	row := q.db.QueryRow(ctx, updateProfileImage, arg.ProfileImage, arg.ID)
	var i UpdateProfileImageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.ProfileImage,
	)
	return i, err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE
    user_sessions
SET
    last_seen_at = NOW()
WHERE
    id = $1
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE
    users
SET
    name = COALESCE($1, name),
    username = COALESCE($2, username),
    phone_number = COALESCE($3, phone_number),
    stripe_customer_id = COALESCE($4, stripe_customer_id),
    updated_at = NOW()
WHERE
    id = $5
`

type UpdateUserParams struct {
	Name             *string   `db:"name" json:"name"`
	Username         *string   `db:"username" json:"username"`
	PhoneNumber      *string   `db:"phone_number" json:"phone_number"`
	StripeCustomerID *string   `db:"stripe_customer_id" json:"stripe_customer_id"`
	ID               uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Name,
		arg.Username,
		arg.PhoneNumber,
		arg.StripeCustomerID,
		arg.ID,
	)
	return err
}
